zeus-file-storage:
  api:
    version: 1.0.0
server:
  port: 8083
spring:
  kafka:
    consumer:
      group-id: file-info-consumer-group
      enable-auto-commit: true
      auto-offset-reset: earliest
    bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:mysql://localhost:3306/filestoragedb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: filestorageapp
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  flyway:
    user: filestorageadmin
    password: password
  profiles:
    active: local, clean
logging:
  file:
    name: logs/local/filestorage.log
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace


